//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.15 at 01:36:40 AM GMT 
//


package org.opencb.biodata.formats.variant.clinvar.vcv.v10jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Used to bundle different types of interpretation (benign , somatic??) ; Clinical significance
 *             with assertion criteria, clinical significance without, reported effects, other.
 *             Supports summary as well as submission details
 * 
 * <p>Java class for typeAggregatedInterpretationSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeAggregatedInterpretationSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Interpretation" type="{}typeAggregatedInterpretation" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeAggregatedInterpretationSet", propOrder = {
    "interpretation"
})
public class TypeAggregatedInterpretationSet {

    @XmlElement(name = "Interpretation", required = true)
    protected List<TypeAggregatedInterpretation> interpretation;

    /**
     * Gets the value of the interpretation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interpretation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterpretation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeAggregatedInterpretation }
     * 
     * 
     */
    public List<TypeAggregatedInterpretation> getInterpretation() {
        if (interpretation == null) {
            interpretation = new ArrayList<TypeAggregatedInterpretation>();
        }
        return this.interpretation;
    }

}
