/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.biodata.models.variant.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Expression { 
  UP, DOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Expression\",\"namespace\":\"org.opencb.biodata.models.variant.avro\",\"symbols\":[\"UP\",\"DOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
