/*
 * Copyright 2015 OpenCB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Variant.proto

package org.opencb.biodata.models.variant.protobuf;

public final class VariantProtos {
  private VariantProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VariantFileAttributesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    java.util.List<org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue> 
        getAttrsList();
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue getAttrs(int index);
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    int getAttrsCount();
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    java.util.List<? extends org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder> 
        getAttrsOrBuilderList();
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder getAttrsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.opencb.biodata.models.variant.protobuf.VariantFileAttributes}
   */
  public static final class VariantFileAttributes extends
      com.google.protobuf.GeneratedMessage
      implements VariantFileAttributesOrBuilder {
    // Use VariantFileAttributes.newBuilder() to construct.
    private VariantFileAttributes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VariantFileAttributes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VariantFileAttributes defaultInstance;
    public static VariantFileAttributes getDefaultInstance() {
      return defaultInstance;
    }

    public VariantFileAttributes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VariantFileAttributes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                attrs_ = new java.util.ArrayList<org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              attrs_.add(input.readMessage(org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          attrs_ = java.util.Collections.unmodifiableList(attrs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.class, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.Builder.class);
    }

    public static com.google.protobuf.Parser<VariantFileAttributes> PARSER =
        new com.google.protobuf.AbstractParser<VariantFileAttributes>() {
      public VariantFileAttributes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VariantFileAttributes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VariantFileAttributes> getParserForType() {
      return PARSER;
    }

    public interface KeyValueOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string key = 1;
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * Key of the pair 
       * </pre>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * Key of the pair 
       * </pre>
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * Key of the pair 
       * </pre>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // required string value = 2;
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       * Value of the pair 
       * </pre>
       */
      boolean hasValue();
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       * Value of the pair 
       * </pre>
       */
      java.lang.String getValue();
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       * Value of the pair 
       * </pre>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue}
     */
    public static final class KeyValue extends
        com.google.protobuf.GeneratedMessage
        implements KeyValueOrBuilder {
      // Use KeyValue.newBuilder() to construct.
      private KeyValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private KeyValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final KeyValue defaultInstance;
      public static KeyValue getDefaultInstance() {
        return defaultInstance;
      }

      public KeyValue getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private KeyValue(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.class, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder.class);
      }

      public static com.google.protobuf.Parser<KeyValue> PARSER =
          new com.google.protobuf.AbstractParser<KeyValue>() {
        public KeyValue parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new KeyValue(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<KeyValue> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * Key of the pair 
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * Key of the pair 
       * </pre>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * Key of the pair 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       * Value of the pair 
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       * Value of the pair 
       * </pre>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       * Value of the pair 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.class, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder.class);
        }

        // Construct using org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_descriptor;
        }

        public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue getDefaultInstanceForType() {
          return org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.getDefaultInstance();
        }

        public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue build() {
          org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue buildPartial() {
          org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue result = new org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue) {
            return mergeFrom((org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue other) {
          if (other == org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string key = 1;
        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         *
         * <pre>
         * Key of the pair 
         * </pre>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         *
         * <pre>
         * Key of the pair 
         * </pre>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         *
         * <pre>
         * Key of the pair 
         * </pre>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         *
         * <pre>
         * Key of the pair 
         * </pre>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         *
         * <pre>
         * Key of the pair 
         * </pre>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         *
         * <pre>
         * Key of the pair 
         * </pre>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // required string value = 2;
        private java.lang.Object value_ = "";
        /**
         * <code>required string value = 2;</code>
         *
         * <pre>
         * Value of the pair 
         * </pre>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string value = 2;</code>
         *
         * <pre>
         * Value of the pair 
         * </pre>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         *
         * <pre>
         * Value of the pair 
         * </pre>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         *
         * <pre>
         * Value of the pair 
         * </pre>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         *
         * <pre>
         * Value of the pair 
         * </pre>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         *
         * <pre>
         * Value of the pair 
         * </pre>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue)
      }

      static {
        defaultInstance = new KeyValue(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue)
    }

    // repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;
    public static final int ATTRS_FIELD_NUMBER = 1;
    private java.util.List<org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue> attrs_;
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    public java.util.List<org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue> getAttrsList() {
      return attrs_;
    }
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    public java.util.List<? extends org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder> 
        getAttrsOrBuilderList() {
      return attrs_;
    }
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    public int getAttrsCount() {
      return attrs_.size();
    }
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue getAttrs(int index) {
      return attrs_.get(index);
    }
    /**
     * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
     */
    public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder getAttrsOrBuilder(
        int index) {
      return attrs_.get(index);
    }

    private void initFields() {
      attrs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getAttrsCount(); i++) {
        if (!getAttrs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < attrs_.size(); i++) {
        output.writeMessage(1, attrs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < attrs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, attrs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.opencb.biodata.models.variant.protobuf.VariantFileAttributes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.class, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.Builder.class);
      }

      // Construct using org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttrsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (attrsBuilder_ == null) {
          attrs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          attrsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_descriptor;
      }

      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes getDefaultInstanceForType() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.getDefaultInstance();
      }

      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes build() {
        org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes buildPartial() {
        org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes result = new org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes(this);
        int from_bitField0_ = bitField0_;
        if (attrsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            attrs_ = java.util.Collections.unmodifiableList(attrs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.attrs_ = attrs_;
        } else {
          result.attrs_ = attrsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes) {
          return mergeFrom((org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes other) {
        if (other == org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.getDefaultInstance()) return this;
        if (attrsBuilder_ == null) {
          if (!other.attrs_.isEmpty()) {
            if (attrs_.isEmpty()) {
              attrs_ = other.attrs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAttrsIsMutable();
              attrs_.addAll(other.attrs_);
            }
            onChanged();
          }
        } else {
          if (!other.attrs_.isEmpty()) {
            if (attrsBuilder_.isEmpty()) {
              attrsBuilder_.dispose();
              attrsBuilder_ = null;
              attrs_ = other.attrs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              attrsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttrsFieldBuilder() : null;
            } else {
              attrsBuilder_.addAllMessages(other.attrs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAttrsCount(); i++) {
          if (!getAttrs(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;
      private java.util.List<org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue> attrs_ =
        java.util.Collections.emptyList();
      private void ensureAttrsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          attrs_ = new java.util.ArrayList<org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue>(attrs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder> attrsBuilder_;

      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public java.util.List<org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue> getAttrsList() {
        if (attrsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attrs_);
        } else {
          return attrsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public int getAttrsCount() {
        if (attrsBuilder_ == null) {
          return attrs_.size();
        } else {
          return attrsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue getAttrs(int index) {
        if (attrsBuilder_ == null) {
          return attrs_.get(index);
        } else {
          return attrsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder setAttrs(
          int index, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue value) {
        if (attrsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttrsIsMutable();
          attrs_.set(index, value);
          onChanged();
        } else {
          attrsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder setAttrs(
          int index, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder builderForValue) {
        if (attrsBuilder_ == null) {
          ensureAttrsIsMutable();
          attrs_.set(index, builderForValue.build());
          onChanged();
        } else {
          attrsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder addAttrs(org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue value) {
        if (attrsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttrsIsMutable();
          attrs_.add(value);
          onChanged();
        } else {
          attrsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder addAttrs(
          int index, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue value) {
        if (attrsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttrsIsMutable();
          attrs_.add(index, value);
          onChanged();
        } else {
          attrsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder addAttrs(
          org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder builderForValue) {
        if (attrsBuilder_ == null) {
          ensureAttrsIsMutable();
          attrs_.add(builderForValue.build());
          onChanged();
        } else {
          attrsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder addAttrs(
          int index, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder builderForValue) {
        if (attrsBuilder_ == null) {
          ensureAttrsIsMutable();
          attrs_.add(index, builderForValue.build());
          onChanged();
        } else {
          attrsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder addAllAttrs(
          java.lang.Iterable<? extends org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue> values) {
        if (attrsBuilder_ == null) {
          ensureAttrsIsMutable();
          super.addAll(values, attrs_);
          onChanged();
        } else {
          attrsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder clearAttrs() {
        if (attrsBuilder_ == null) {
          attrs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          attrsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public Builder removeAttrs(int index) {
        if (attrsBuilder_ == null) {
          ensureAttrsIsMutable();
          attrs_.remove(index);
          onChanged();
        } else {
          attrsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder getAttrsBuilder(
          int index) {
        return getAttrsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder getAttrsOrBuilder(
          int index) {
        if (attrsBuilder_ == null) {
          return attrs_.get(index);  } else {
          return attrsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public java.util.List<? extends org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder> 
           getAttrsOrBuilderList() {
        if (attrsBuilder_ != null) {
          return attrsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attrs_);
        }
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder addAttrsBuilder() {
        return getAttrsFieldBuilder().addBuilder(
            org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder addAttrsBuilder(
          int index) {
        return getAttrsFieldBuilder().addBuilder(
            index, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .org.opencb.biodata.models.variant.protobuf.VariantFileAttributes.KeyValue attrs = 1;</code>
       */
      public java.util.List<org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder> 
           getAttrsBuilderList() {
        return getAttrsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder> 
          getAttrsFieldBuilder() {
        if (attrsBuilder_ == null) {
          attrsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValue.Builder, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantFileAttributes.KeyValueOrBuilder>(
                  attrs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          attrs_ = null;
        }
        return attrsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.opencb.biodata.models.variant.protobuf.VariantFileAttributes)
    }

    static {
      defaultInstance = new VariantFileAttributes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.opencb.biodata.models.variant.protobuf.VariantFileAttributes)
  }

  public interface VariantSampleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string sample = 1;
    /**
     * <code>required string sample = 1;</code>
     */
    boolean hasSample();
    /**
     * <code>required string sample = 1;</code>
     */
    java.lang.String getSample();
    /**
     * <code>required string sample = 1;</code>
     */
    com.google.protobuf.ByteString
        getSampleBytes();
  }
  /**
   * Protobuf type {@code org.opencb.biodata.models.variant.protobuf.VariantSample}
   */
  public static final class VariantSample extends
      com.google.protobuf.GeneratedMessage
      implements VariantSampleOrBuilder {
    // Use VariantSample.newBuilder() to construct.
    private VariantSample(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VariantSample(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VariantSample defaultInstance;
    public static VariantSample getDefaultInstance() {
      return defaultInstance;
    }

    public VariantSample getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VariantSample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sample_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample.class, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample.Builder.class);
    }

    public static com.google.protobuf.Parser<VariantSample> PARSER =
        new com.google.protobuf.AbstractParser<VariantSample>() {
      public VariantSample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VariantSample(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VariantSample> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string sample = 1;
    public static final int SAMPLE_FIELD_NUMBER = 1;
    private java.lang.Object sample_;
    /**
     * <code>required string sample = 1;</code>
     */
    public boolean hasSample() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sample = 1;</code>
     */
    public java.lang.String getSample() {
      java.lang.Object ref = sample_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sample_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sample = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSampleBytes() {
      java.lang.Object ref = sample_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sample_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sample_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSample()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSampleBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSampleBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.opencb.biodata.models.variant.protobuf.VariantSample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample.class, org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample.Builder.class);
      }

      // Construct using org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sample_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_descriptor;
      }

      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample getDefaultInstanceForType() {
        return org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample.getDefaultInstance();
      }

      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample build() {
        org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample buildPartial() {
        org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample result = new org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sample_ = sample_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample) {
          return mergeFrom((org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample other) {
        if (other == org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample.getDefaultInstance()) return this;
        if (other.hasSample()) {
          bitField0_ |= 0x00000001;
          sample_ = other.sample_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSample()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opencb.biodata.models.variant.protobuf.VariantProtos.VariantSample) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string sample = 1;
      private java.lang.Object sample_ = "";
      /**
       * <code>required string sample = 1;</code>
       */
      public boolean hasSample() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sample = 1;</code>
       */
      public java.lang.String getSample() {
        java.lang.Object ref = sample_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sample_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sample = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSampleBytes() {
        java.lang.Object ref = sample_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sample_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sample = 1;</code>
       */
      public Builder setSample(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sample_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sample = 1;</code>
       */
      public Builder clearSample() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sample_ = getDefaultInstance().getSample();
        onChanged();
        return this;
      }
      /**
       * <code>required string sample = 1;</code>
       */
      public Builder setSampleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sample_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.opencb.biodata.models.variant.protobuf.VariantSample)
    }

    static {
      defaultInstance = new VariantSample(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.opencb.biodata.models.variant.protobuf.VariantSample)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rVariant.proto\022*org.opencb.biodata.mode" +
      "ls.variant.protobuf\"\232\001\n\025VariantFileAttri" +
      "butes\022Y\n\005attrs\030\001 \003(\0132J.org.opencb.biodat" +
      "a.models.variant.protobuf.VariantFileAtt" +
      "ributes.KeyValue\032&\n\010KeyValue\022\013\n\003key\030\001 \002(" +
      "\t\022\r\n\005value\030\002 \002(\t\"\037\n\rVariantSample\022\016\n\006sam" +
      "ple\030\001 \002(\tB\017B\rVariantProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_descriptor,
              new java.lang.String[] { "Attrs", });
          internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_descriptor =
            internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_descriptor.getNestedTypes().get(0);
          internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_opencb_biodata_models_variant_protobuf_VariantFileAttributes_KeyValue_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_opencb_biodata_models_variant_protobuf_VariantSample_descriptor,
              new java.lang.String[] { "Sample", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
