//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 11:40:12 AM BST 
//


package org.opencb.biodata.formats.drug.drugbank.v43jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opencb.biodata.formats.drug.drugbank.v43jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Drugbank_QNAME = new QName("http://www.drugbank.ca", "drugbank");
    private final static QName _SnpAdverseDrugReactionTypePubmedId_QNAME = new QName("http://www.drugbank.ca", "pubmed-id");
    private final static QName _SnpAdverseDrugReactionTypeAllele_QNAME = new QName("http://www.drugbank.ca", "allele");
    private final static QName _SnpAdverseDrugReactionTypeUniprotId_QNAME = new QName("http://www.drugbank.ca", "uniprot-id");
    private final static QName _SnpAdverseDrugReactionTypeProteinName_QNAME = new QName("http://www.drugbank.ca", "protein-name");
    private final static QName _SnpAdverseDrugReactionTypeDescription_QNAME = new QName("http://www.drugbank.ca", "description");
    private final static QName _SnpAdverseDrugReactionTypeAdverseReaction_QNAME = new QName("http://www.drugbank.ca", "adverse-reaction");
    private final static QName _SnpAdverseDrugReactionTypeGeneSymbol_QNAME = new QName("http://www.drugbank.ca", "gene-symbol");
    private final static QName _SnpAdverseDrugReactionTypeRsId_QNAME = new QName("http://www.drugbank.ca", "rs-id");
    private final static QName _SnpEffectTypeDefiningChange_QNAME = new QName("http://www.drugbank.ca", "defining-change");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opencb.biodata.formats.drug.drugbank.v43jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PolypeptideType }
     * 
     */
    public PolypeptideType createPolypeptideType() {
        return new PolypeptideType();
    }

    /**
     * Create an instance of {@link SequenceListType }
     * 
     */
    public SequenceListType createSequenceListType() {
        return new SequenceListType();
    }

    /**
     * Create an instance of {@link PriceType }
     * 
     */
    public PriceType createPriceType() {
        return new PriceType();
    }

    /**
     * Create an instance of {@link DrugbankType }
     * 
     */
    public DrugbankType createDrugbankType() {
        return new DrugbankType();
    }

    /**
     * Create an instance of {@link PfamListType }
     * 
     */
    public PfamListType createPfamListType() {
        return new PfamListType();
    }

    /**
     * Create an instance of {@link SaltType }
     * 
     */
    public SaltType createSaltType() {
        return new SaltType();
    }

    /**
     * Create an instance of {@link SnpEffectListType }
     * 
     */
    public SnpEffectListType createSnpEffectListType() {
        return new SnpEffectListType();
    }

    /**
     * Create an instance of {@link GoClassifierListType }
     * 
     */
    public GoClassifierListType createGoClassifierListType() {
        return new GoClassifierListType();
    }

    /**
     * Create an instance of {@link PathwayDrugListType }
     * 
     */
    public PathwayDrugListType createPathwayDrugListType() {
        return new PathwayDrugListType();
    }

    /**
     * Create an instance of {@link PolypeptideSynonymListType }
     * 
     */
    public PolypeptideSynonymListType createPolypeptideSynonymListType() {
        return new PolypeptideSynonymListType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     * 
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

    /**
     * Create an instance of {@link TargetType }
     * 
     */
    public TargetType createTargetType() {
        return new TargetType();
    }

    /**
     * Create an instance of {@link AtcCodeType }
     * 
     */
    public AtcCodeType createAtcCodeType() {
        return new AtcCodeType();
    }

    /**
     * Create an instance of {@link ExperimentalPropertyType }
     * 
     */
    public ExperimentalPropertyType createExperimentalPropertyType() {
        return new ExperimentalPropertyType();
    }

    /**
     * Create an instance of {@link DrugbankDrugIdType }
     * 
     */
    public DrugbankDrugIdType createDrugbankDrugIdType() {
        return new DrugbankDrugIdType();
    }

    /**
     * Create an instance of {@link SequenceType }
     * 
     */
    public SequenceType createSequenceType() {
        return new SequenceType();
    }

    /**
     * Create an instance of {@link PfamType }
     * 
     */
    public PfamType createPfamType() {
        return new PfamType();
    }

    /**
     * Create an instance of {@link AtcCodeLevelType }
     * 
     */
    public AtcCodeLevelType createAtcCodeLevelType() {
        return new AtcCodeLevelType();
    }

    /**
     * Create an instance of {@link PolypeptideListType }
     * 
     */
    public PolypeptideListType createPolypeptideListType() {
        return new PolypeptideListType();
    }

    /**
     * Create an instance of {@link ExperimentalPropertyListType }
     * 
     */
    public ExperimentalPropertyListType createExperimentalPropertyListType() {
        return new ExperimentalPropertyListType();
    }

    /**
     * Create an instance of {@link CategoryListType }
     * 
     */
    public CategoryListType createCategoryListType() {
        return new CategoryListType();
    }

    /**
     * Create an instance of {@link PriceListType }
     * 
     */
    public PriceListType createPriceListType() {
        return new PriceListType();
    }

    /**
     * Create an instance of {@link InternationalBrandListType }
     * 
     */
    public InternationalBrandListType createInternationalBrandListType() {
        return new InternationalBrandListType();
    }

    /**
     * Create an instance of {@link ExternalIdentifierType }
     * 
     */
    public ExternalIdentifierType createExternalIdentifierType() {
        return new ExternalIdentifierType();
    }

    /**
     * Create an instance of {@link CarrierType }
     * 
     */
    public CarrierType createCarrierType() {
        return new CarrierType();
    }

    /**
     * Create an instance of {@link PackagerType }
     * 
     */
    public PackagerType createPackagerType() {
        return new PackagerType();
    }

    /**
     * Create an instance of {@link ExternalLinkType }
     * 
     */
    public ExternalLinkType createExternalLinkType() {
        return new ExternalLinkType();
    }

    /**
     * Create an instance of {@link DrugbankMetaboliteIdType }
     * 
     */
    public DrugbankMetaboliteIdType createDrugbankMetaboliteIdType() {
        return new DrugbankMetaboliteIdType();
    }

    /**
     * Create an instance of {@link ReactionEnzymeListType }
     * 
     */
    public ReactionEnzymeListType createReactionEnzymeListType() {
        return new ReactionEnzymeListType();
    }

    /**
     * Create an instance of {@link ManufacturerType }
     * 
     */
    public ManufacturerType createManufacturerType() {
        return new ManufacturerType();
    }

    /**
     * Create an instance of {@link AtcCodeListType }
     * 
     */
    public AtcCodeListType createAtcCodeListType() {
        return new AtcCodeListType();
    }

    /**
     * Create an instance of {@link MixtureListType }
     * 
     */
    public MixtureListType createMixtureListType() {
        return new MixtureListType();
    }

    /**
     * Create an instance of {@link SynonymType }
     * 
     */
    public SynonymType createSynonymType() {
        return new SynonymType();
    }

    /**
     * Create an instance of {@link PatentListType }
     * 
     */
    public PatentListType createPatentListType() {
        return new PatentListType();
    }

    /**
     * Create an instance of {@link CalculatedPropertyType }
     * 
     */
    public CalculatedPropertyType createCalculatedPropertyType() {
        return new CalculatedPropertyType();
    }

    /**
     * Create an instance of {@link ExternalIdentifierListType }
     * 
     */
    public ExternalIdentifierListType createExternalIdentifierListType() {
        return new ExternalIdentifierListType();
    }

    /**
     * Create an instance of {@link PathwayEnzymeListType }
     * 
     */
    public PathwayEnzymeListType createPathwayEnzymeListType() {
        return new PathwayEnzymeListType();
    }

    /**
     * Create an instance of {@link ReactionListType }
     * 
     */
    public ReactionListType createReactionListType() {
        return new ReactionListType();
    }

    /**
     * Create an instance of {@link SnpEffectType }
     * 
     */
    public SnpEffectType createSnpEffectType() {
        return new SnpEffectType();
    }

    /**
     * Create an instance of {@link PolypeptideExternalIdentifierType }
     * 
     */
    public PolypeptideExternalIdentifierType createPolypeptideExternalIdentifierType() {
        return new PolypeptideExternalIdentifierType();
    }

    /**
     * Create an instance of {@link PatentType }
     * 
     */
    public PatentType createPatentType() {
        return new PatentType();
    }

    /**
     * Create an instance of {@link TransporterListType }
     * 
     */
    public TransporterListType createTransporterListType() {
        return new TransporterListType();
    }

    /**
     * Create an instance of {@link DosageListType }
     * 
     */
    public DosageListType createDosageListType() {
        return new DosageListType();
    }

    /**
     * Create an instance of {@link EnzymeListType }
     * 
     */
    public EnzymeListType createEnzymeListType() {
        return new EnzymeListType();
    }

    /**
     * Create an instance of {@link PathwayListType }
     * 
     */
    public PathwayListType createPathwayListType() {
        return new PathwayListType();
    }

    /**
     * Create an instance of {@link CarrierListType }
     * 
     */
    public CarrierListType createCarrierListType() {
        return new CarrierListType();
    }

    /**
     * Create an instance of {@link DrugInteractionListType }
     * 
     */
    public DrugInteractionListType createDrugInteractionListType() {
        return new DrugInteractionListType();
    }

    /**
     * Create an instance of {@link SynonymListType }
     * 
     */
    public SynonymListType createSynonymListType() {
        return new SynonymListType();
    }

    /**
     * Create an instance of {@link FoodInteractionListType }
     * 
     */
    public FoodInteractionListType createFoodInteractionListType() {
        return new FoodInteractionListType();
    }

    /**
     * Create an instance of {@link EnzymeType }
     * 
     */
    public EnzymeType createEnzymeType() {
        return new EnzymeType();
    }

    /**
     * Create an instance of {@link ReactionElementType }
     * 
     */
    public ReactionElementType createReactionElementType() {
        return new ReactionElementType();
    }

    /**
     * Create an instance of {@link PackagerListType }
     * 
     */
    public PackagerListType createPackagerListType() {
        return new PackagerListType();
    }

    /**
     * Create an instance of {@link SnpAdverseDrugReactionType }
     * 
     */
    public SnpAdverseDrugReactionType createSnpAdverseDrugReactionType() {
        return new SnpAdverseDrugReactionType();
    }

    /**
     * Create an instance of {@link ReactionType }
     * 
     */
    public ReactionType createReactionType() {
        return new ReactionType();
    }

    /**
     * Create an instance of {@link MixtureType }
     * 
     */
    public MixtureType createMixtureType() {
        return new MixtureType();
    }

    /**
     * Create an instance of {@link CalculatedPropertyListType }
     * 
     */
    public CalculatedPropertyListType createCalculatedPropertyListType() {
        return new CalculatedPropertyListType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link SaltListType }
     * 
     */
    public SaltListType createSaltListType() {
        return new SaltListType();
    }

    /**
     * Create an instance of {@link ProductListType }
     * 
     */
    public ProductListType createProductListType() {
        return new ProductListType();
    }

    /**
     * Create an instance of {@link AffectedOrganismListType }
     * 
     */
    public AffectedOrganismListType createAffectedOrganismListType() {
        return new AffectedOrganismListType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link AhfsCodeListType }
     * 
     */
    public AhfsCodeListType createAhfsCodeListType() {
        return new AhfsCodeListType();
    }

    /**
     * Create an instance of {@link SnpAdverseDrugReactionListType }
     * 
     */
    public SnpAdverseDrugReactionListType createSnpAdverseDrugReactionListType() {
        return new SnpAdverseDrugReactionListType();
    }

    /**
     * Create an instance of {@link GoClassifierType }
     * 
     */
    public GoClassifierType createGoClassifierType() {
        return new GoClassifierType();
    }

    /**
     * Create an instance of {@link ExternalLinkListType }
     * 
     */
    public ExternalLinkListType createExternalLinkListType() {
        return new ExternalLinkListType();
    }

    /**
     * Create an instance of {@link PathwayDrugType }
     * 
     */
    public PathwayDrugType createPathwayDrugType() {
        return new PathwayDrugType();
    }

    /**
     * Create an instance of {@link ActionListType }
     * 
     */
    public ActionListType createActionListType() {
        return new ActionListType();
    }

    /**
     * Create an instance of {@link DrugType }
     * 
     */
    public DrugType createDrugType() {
        return new DrugType();
    }

    /**
     * Create an instance of {@link DrugInteractionType }
     * 
     */
    public DrugInteractionType createDrugInteractionType() {
        return new DrugInteractionType();
    }

    /**
     * Create an instance of {@link ReactionEnzymeType }
     * 
     */
    public ReactionEnzymeType createReactionEnzymeType() {
        return new ReactionEnzymeType();
    }

    /**
     * Create an instance of {@link TargetListType }
     * 
     */
    public TargetListType createTargetListType() {
        return new TargetListType();
    }

    /**
     * Create an instance of {@link PolypeptideExternalIdentifierListType }
     * 
     */
    public PolypeptideExternalIdentifierListType createPolypeptideExternalIdentifierListType() {
        return new PolypeptideExternalIdentifierListType();
    }

    /**
     * Create an instance of {@link TransporterType }
     * 
     */
    public TransporterType createTransporterType() {
        return new TransporterType();
    }

    /**
     * Create an instance of {@link GroupListType }
     * 
     */
    public GroupListType createGroupListType() {
        return new GroupListType();
    }

    /**
     * Create an instance of {@link DosageType }
     * 
     */
    public DosageType createDosageType() {
        return new DosageType();
    }

    /**
     * Create an instance of {@link DrugbankSaltIdType }
     * 
     */
    public DrugbankSaltIdType createDrugbankSaltIdType() {
        return new DrugbankSaltIdType();
    }

    /**
     * Create an instance of {@link InternationalBrandType }
     * 
     */
    public InternationalBrandType createInternationalBrandType() {
        return new InternationalBrandType();
    }

    /**
     * Create an instance of {@link PathwayType }
     * 
     */
    public PathwayType createPathwayType() {
        return new PathwayType();
    }

    /**
     * Create an instance of {@link ManufacturerListType }
     * 
     */
    public ManufacturerListType createManufacturerListType() {
        return new ManufacturerListType();
    }

    /**
     * Create an instance of {@link PolypeptideType.Organism }
     * 
     */
    public PolypeptideType.Organism createPolypeptideTypeOrganism() {
        return new PolypeptideType.Organism();
    }

    /**
     * Create an instance of {@link SequenceListType.Sequence }
     * 
     */
    public SequenceListType.Sequence createSequenceListTypeSequence() {
        return new SequenceListType.Sequence();
    }

    /**
     * Create an instance of {@link PriceType.Cost }
     * 
     */
    public PriceType.Cost createPriceTypeCost() {
        return new PriceType.Cost();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrugbankType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "drugbank")
    public JAXBElement<DrugbankType> createDrugbank(DrugbankType value) {
        return new JAXBElement<DrugbankType>(_Drugbank_QNAME, DrugbankType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "pubmed-id", scope = SnpAdverseDrugReactionType.class)
    public JAXBElement<String> createSnpAdverseDrugReactionTypePubmedId(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypePubmedId_QNAME, String.class, SnpAdverseDrugReactionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "allele", scope = SnpAdverseDrugReactionType.class)
    public JAXBElement<String> createSnpAdverseDrugReactionTypeAllele(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeAllele_QNAME, String.class, SnpAdverseDrugReactionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "uniprot-id", scope = SnpAdverseDrugReactionType.class)
    public JAXBElement<String> createSnpAdverseDrugReactionTypeUniprotId(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeUniprotId_QNAME, String.class, SnpAdverseDrugReactionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "protein-name", scope = SnpAdverseDrugReactionType.class)
    public JAXBElement<String> createSnpAdverseDrugReactionTypeProteinName(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeProteinName_QNAME, String.class, SnpAdverseDrugReactionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "description", scope = SnpAdverseDrugReactionType.class)
    public JAXBElement<String> createSnpAdverseDrugReactionTypeDescription(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeDescription_QNAME, String.class, SnpAdverseDrugReactionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "adverse-reaction", scope = SnpAdverseDrugReactionType.class)
    public JAXBElement<String> createSnpAdverseDrugReactionTypeAdverseReaction(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeAdverseReaction_QNAME, String.class, SnpAdverseDrugReactionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "gene-symbol", scope = SnpAdverseDrugReactionType.class)
    public JAXBElement<String> createSnpAdverseDrugReactionTypeGeneSymbol(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeGeneSymbol_QNAME, String.class, SnpAdverseDrugReactionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "rs-id", scope = SnpAdverseDrugReactionType.class)
    public JAXBElement<String> createSnpAdverseDrugReactionTypeRsId(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeRsId_QNAME, String.class, SnpAdverseDrugReactionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "pubmed-id", scope = SnpEffectType.class)
    public JAXBElement<String> createSnpEffectTypePubmedId(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypePubmedId_QNAME, String.class, SnpEffectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "allele", scope = SnpEffectType.class)
    public JAXBElement<String> createSnpEffectTypeAllele(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeAllele_QNAME, String.class, SnpEffectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "uniprot-id", scope = SnpEffectType.class)
    public JAXBElement<String> createSnpEffectTypeUniprotId(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeUniprotId_QNAME, String.class, SnpEffectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "protein-name", scope = SnpEffectType.class)
    public JAXBElement<String> createSnpEffectTypeProteinName(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeProteinName_QNAME, String.class, SnpEffectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "description", scope = SnpEffectType.class)
    public JAXBElement<String> createSnpEffectTypeDescription(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeDescription_QNAME, String.class, SnpEffectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "defining-change", scope = SnpEffectType.class)
    public JAXBElement<String> createSnpEffectTypeDefiningChange(String value) {
        return new JAXBElement<String>(_SnpEffectTypeDefiningChange_QNAME, String.class, SnpEffectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "gene-symbol", scope = SnpEffectType.class)
    public JAXBElement<String> createSnpEffectTypeGeneSymbol(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeGeneSymbol_QNAME, String.class, SnpEffectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.drugbank.ca", name = "rs-id", scope = SnpEffectType.class)
    public JAXBElement<String> createSnpEffectTypeRsId(String value) {
        return new JAXBElement<String>(_SnpAdverseDrugReactionTypeRsId_QNAME, String.class, SnpEffectType.class, value);
    }

}
