//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.25 at 11:40:12 AM BST 
//


package org.opencb.biodata.formats.drug.drugbank.v43jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for polypeptide-external-identifier-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="polypeptide-external-identifier-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resource" type="{http://www.drugbank.ca}polypeptide-external-identifier-resource-type"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "polypeptide-external-identifier-type", propOrder = {
    "resource",
    "identifier"
})
public class PolypeptideExternalIdentifierType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PolypeptideExternalIdentifierResourceType resource;
    @XmlElement(required = true)
    protected String identifier;

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link PolypeptideExternalIdentifierResourceType }
     *     
     */
    public PolypeptideExternalIdentifierResourceType getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolypeptideExternalIdentifierResourceType }
     *     
     */
    public void setResource(PolypeptideExternalIdentifierResourceType value) {
        this.resource = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

}
