name: Push biodata develop

on:
  push:
    branches:
      - develop
      - release-*

jobs:
  build:
    uses: opencb/ci-core/.github/workflows/build.yml@main
    with:
      needs_hadoop_preparation: false
      upload_artifact: false
      dependency_repos: "java-common-libs"
    secrets: inherit

  test:
    name: Test and push Sonar analysis
    needs: build
    uses: opencb/ci-core/.github/workflows/test.yml@main
    with:
      cache_key: true
    secrets: inherit

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@develop
    needs: test
    with:
      maven_opts: -U -DskipTests
      cache_key: ${{ needs.test.outputs.cache_key }}
    secrets: inherit
