name: Push biodata develop
run-name: 'Push on ${{ github.ref_name }} by @${{ github.actor }}'

on:
  push:
    branches:
      - develop
      - release-*
      - TASK-*

jobs:
  build:
    uses: opencb/ci-core/.github/workflows/build.yml@main
    with:
      upload_artifact: false
      dependency_repos: "java-common-libs"
      deploy_maven: ${{ !startsWith(github.ref_name, 'TASK-') }}
    secrets: inherit

  test:
    name: Test and push Sonar analysis
    needs: build
    uses: opencb/ci-core/.github/workflows/test.yml@main
    with:
      cache_key: true
    secrets: inherit

