name: Pull request approve workflow
run-name: 'Pull request approve workflow ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} by @${{ github.actor }}'

on:
  pull_request_review:
    types: [ submitted ]

jobs:

  test-xetabase:
    uses: opencb/ci-core/.github/workflows/pull-request-approve.yml@main
    with:
      target_branch: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref }}
    secrets: inherit

