name: Release new biodata version

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: opencb/ci-core/.github/workflows/build.yml@main
    with:
      needs_hadoop_preparation: false
      upload_artifact: false
      dependency_repos: "java-common-libs"
      deploy_maven: true
    secrets: inherit

  release:
    uses: opencb/ci-core/.github/workflows/release.yml@main
    needs: build
