name: Push biodata task

on:
  push:
    branches:
      - TASK-*

jobs:
  build:
    uses: opencb/ci-core/.github/workflows/build.yml@main
    with:
      upload_artifact: false
      dependency_repos: "java-common-libs"
    secrets: inherit

  test:
    name: Test and push Sonar analysis
    needs: build
    uses: opencb/ci-core/.github/workflows/test.yml@main
    with:
      cache_key: true
    secrets: inherit