name: Push biodata task

on:
  push:
    branches:
      - TASK-*

jobs:

  build:
    uses: opencb/ci-core/.github/workflows/build.yml@main
    with:
      upload_artifact: false
      dependency_repos: "java-common-libs"
      deploy_maven: false
    secrets: inherit

  test:
    name: Test and push Sonar analysis
    needs: build
    uses: opencb/ci-core/.github/workflows/test.yml@main
    with:
      cache_key: true
    secrets: inherit

  test-xetabase:
    uses: opencb/ci-core/.github/workflows/pull-request-approve.yml@main
    with:
      target_branch: develop
      head_ref: TASK-8067
    secrets: inherit